version: '3.8'
services:
  expense_tracker:
    image: localhost:5000/heitor582/expense_tracker:latest
    deploy:
      replicas: 3
      endpoint_mode: vip
    ports:
      - 8090-8092:8080
    depends_on: [expense_tracker_postgres, rabbitmq]
    networks:
     - server-network
     - kafka-network
    env_file:
      - .env

  expense_tracker_postgres:
    image: postgres
    container_name: expense_tracker_postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    networks:
     - server-network
     - kafka-network
    env_file:
      - .env
    volumes:
      - expense_tracker_postgres_data:/var/lib/postgresql/data

networks:
  server-network:
    external: true
  kafka-network:
    external: true

volumes:
  expense_tracker_postgres_data: