api:
  insecure: true
  dashboard: true
  debug: true

accessLog: {}
log:
  level: DEBUG

entryPoints:
  web:
    address: :80
  websecure:
    address: :443

providers:
  docker:
    exposedByDefault: false